# list of directories to backup
source_directories:
  - ""

# list of borg repositories to backup data into
repositories:
  - path: ""    # path to repository
    label: ""   # name of repository (optional)

# file/directory patterns to exclude from backups (regex)
exclude_patterns:
  - "*.DS_Store"    # exclusive for macOS
  - "*.localized"   # exclusive for macOS

# files/directories to exclude if contains the following
exclude_if_present:
  - ".nobackup"

# set pruning options of stale data backups
keep_within: 3H     # all backups made within N sec/min/hrs will be kept
keep_daily: 2       # the last N backups made today will be kept
kept_weekly: 7      # the last N backups made this week will be kept
kept_monthly: 14    # the last N backups made this month will be kept
kept_yearly: 24     # the last N backups made this year will be kept

# shell command to obtain borg repository password
encryption_passcommand: ""

# temporary caching location for borgmatic operations
borgmatic_source_directory: "/tmp/borgmatic/"

# error handling on failed access attempts
retries: 3        # retry N times before exiting
retry_wait: 10    # wait N seconds before retrying

